### ISSUE TITLE
NPC_RemoveInventory (performance)

### ISSUE THREAD

**Issue by damianut** [Bad-Scientists/AF-Script-Packet#26]
Somebody clever wrote: _Yes, it would probably be best to abstract the inside of NPC_RemoveInventoryCategory into a internal function and expose cleaner API._

To avoid calling `Hlp_IsValidNpc` 8 times.

**Comment by auronen** [comment]
References this https://github.com/auronen/AF-Script-Packet/blob/7bfb0a55b052d9745e87cfc7ff5a5efb8524c92b/inventory_oCNpc.d#L1415-L1462 part of the code.

**Comment by kirides** [comment]
Iirc. G2 does not have categories and always returns all items for any category index, thus to improve perf in g2 one would only have to run it once.

**Comment by Fawkes-dev** [comment]
Thank you all for your feedback! Did some more optimizations in 842838f and a9830ec so hopefully it's better.
