### ISSUE TITLE
G12-NoAmmoPrint does not working correctly with Crossbows

### ISSUE THREAD

**Issue by rezu93** [Bad-Scientists/AF-Script-Packet#72]
If you got a bow readied your hero got an arrow in righthand but when you draw crossbow you got only crossbow in your right and lefthand so it cant check if you got a bolt ready but no bolts in EQ and automatically spam that you got no ammo.

**Comment by rezu93** [comment]
if (!count) {
			var int vobPtr; vobPtr = oCNpc_GetSlotItem (slf, "ZS_RIGHTHAND");
			var int vobPtr2; vobPtr2 = oCNpc_GetSlotItem (slf, "ZS_LEFTHAND");
			if (Hlp_Is_oCItem (vobPtr) || Hlp_Is_oCItem (vobPtr2)) {
				var oCItem ammo; ammo = _^ (vobPtr);
				var oCItem ammo2; ammo2 = _^ (vobPtr2);
				if (Hlp_GetInstanceID (ammo) == weapon.munition || Hlp_GetInstanceID (ammo2) == weapon.munition) {
					count = 1;
				};
			};
		};

f.e. it fixed the issue.

**Comment by Fawkes-dev** [comment]
Thank you for the report, fixed in 376d48b.
