### ISSUE TITLE
Undefined class and function [Unable to run the packet]

### ISSUE THREAD

**Issue by damianut** [Bad-Scientists/AF-Script-Packet#81]
[] spatialState.d
    In `Npc_GetWaterDepthKnee` function `zTConfig` class is used, but not defined.

[] Standalone-Packages\G12-Trialogue\trialogue.d
    In `Trialogue_Invite` function `Npc_StartAIState` function is used, but not defined.

**Comment by Fawkes-dev** [comment]
Thank you for the report!
Should be ok now, sorry was pushing some of these changes out of sync over last couple of days.
