### ISSUE TITLE
Ini-entries in dedicated sections

### ISSUE THREAD

**Issue by Wolf-64** [Bad-Scientists/AF-Script-Packet#83]
I was wondering if it would make sense to refactor all instances of user settings made to Gothic.ini to move to their own section in Gothic.ini as suggest by Ikarus author in the readme:

> //BEACHTE:-Falls du neue Optionen einführst gebietet der gute Stil, dass du dies in einer eigenen Sektion tust und die Optionen verständlich benennst! Als Norm schlage ich vor, dass eine Mod mit Namen "myMod" nur in der Sektion "myMod" oder "MOD_mymod" neue Eigenschaften einführt (und nicht etwa in der Sektion "GAME" oder "PERFORMANCE").
(//NOTE:-If you're introducing new options, it's good practice to do so in your own properly named sections! I would suggest the following convention: a mod with the name "myMod" should only write new settings into it's own section "myMod" or "MOD_mymod" and not in sections like "GAME" or "PERFORMANCE".)

So for example settings for Better Bars like this:
`MEM_SetGothOpt ("GAME", "manaBarDisplayMethod", IntToString (_manaBar_DisplayMethod));`
Could be written like this instead:
`MEM_SetGothOpt ("AFSP", "manaBarDisplayMethod", IntToString (_manaBar_DisplayMethod));`

I think it would be a good convention to better distinguish AFSP mod settings in Gothic.ini.

**Comment by Fawkes-dev** [comment]
I think that makes sense - will change it as per your suggestion 👍
